export const SEND_LOGIN_REQUEST = 'SEND_LOGIN_REQUEST';
export const FILL_USER_PAGE = 'FILL_USER_PAGE';
export const FILL_TOPIC_PAGE = 'FILL_TOPIC_PAGE';
export const FILL_COMMENTS = 'FILL_COMMENTS';
export const START_SESSION = 'START_SESSION';
export const FILL_DASHBOARD_PAGE = 'FILL_DASHBOARD';
export const SELECT_POST = 'SELECT_POST';