# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complete', '0002_auto_20170330_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.ManyToManyField(related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
